### PR TITLE
Use travis-ci to run the tests

### PR DESCRIPTION
**Pull request by kylef**
There is currently one test failure, unfortunately I don't know much about how this works. Would you be able to take a look @smizell?

```
FAIL: test_response_for (tests.wrappers_test.TestFlaskAPIResource)

AssertionError: Expected call: mock(<hypermedia_resource.base.HypermediaResource object at 0x7fa89ac95b90>, 'application/hal+json')
Not called
```

### CODE REVIEW

**Comment by honzajavorek** [comment]
Duplicate of #1 ?

**Comment by kylef** [comment]
Sorry, I didn't notice that @honzajavorek. I think this pull-request should supersede #1. That pull-request doesn't configure the development dependencies to run the tests so I don't think it would even get to running the tests.

**Comment by smizell** [comment]
@kylef Thanks for this! I think some of the tests got out of sync from some stuff I worked on at RestFest. This repo needs some attention to get a lot of things in line with the charter, and hopefully I'll be able to address that soon.

This is a big help!

**Comment by kylef** [comment]
@smizell Alright, I've made this failing test skip for now so this is green so this could be merged and that can be worked on later.

**Pull request merged**
